version: '3.3'

services:
  postgres:
    image: postgres:10-alpine
    restart: always
    hostname: postgres
    ports: 
      - "5432"
    volumes:
      - 'postgresdata:/var/lib/postgresql/data'
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks: 
      - production
  web:
    image: diemesleno/pygym
    hostname: web
    build:
      context: .
    volumes:
      - .:/usr/src/pygym
    container_name: web
    ports:
      - "8000:8000"
    links:
      - postgres
    networks: 
      - production
    depends_on:
      - postgres
    command: python3 manage.py runserver 0.0.0.0:8000
volumes:
  postgresdata:
  web:
networks:
   production:
      driver: bridge
